### ISSUE TITLE
UX está quebrada em alguns Browsers

### ISSUE THREAD

**Issue by mjacobus** [mjacobus/predios#67]
Por exemplo, no telefone do @FernandoMassa

**Comment by FernandoMassa** [comment]
???
*Fernando Massa*

*Desenvolvedor de Software*



Em qua, 9 de jan de 2019 às 23:53, Marcelo Jacobus <notifications@github.com>
escreveu:

**Comment by JeronimoLeao** [comment]
Mas olha quem encontro por aqui :D

**Comment by mjacobus** [comment]
Bem vindo @JeronimoLeao !!
